eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: pedidoapi
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    url: jdbc:mysql://localhost:3306/db_ecommerce?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
server:
  error:
    whitelabel:
      enabled: 'false'
  port: ${PORT:0}

management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always

management.health.diskspace.enabled: false
management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: false

info:
    name: ${spring.application.name}
    description: ecommerce pedidoapi
    environment: ${spring.profiles.active}
    version: 0.0.1

management.metrics.tags.application: ${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests: true
management.metrics.distribution.percentiles-histogram.resilience4j.circuitbreaker.calls: true
   
use-resource-role-mappings: 'true'

resilience4j:
  circuitbreaker:
    instances:
        userapi:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            slidingWindowType: COUNT_BASED
        produtoapi:
            registerHealthIndicator: true
            slidingWindowSize: 10
            minimumNumberOfCalls: 5
            permittedNumberOfCallsInHalfOpenState: 3
            automaticTransitionFromOpenToHalfOpenEnabled: true
            waitDurationInOpenState: 5s
            failureRateThreshold: 50
            slidingWindowType: COUNT_BASED
            
#  retry:
#     instances:
#      userapi:
#        maxAttempts: 5
#        waitDuration: 5s  
#      produtoapi:
#        maxAttempts: 5
#        waitDuration: 5s   

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    operationsSorter: method
    use-root-path: 'true'
    disable-swagger-default-url: 'true'
    path: /swagger-ui.html
  packagesToScan: com.ecommerce.pedidoapi.controller  
 
